spring:
  application:
    name: light
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:mapper1/*.xml
  type-aliases-package: com.dzq.**.entity
#不校验登录 白名单url
security:
  ignore:
    whites:
      - /task/**
      - /druid/**
      - /error/**
      - /captcha/captcha
      - /login.jsp
      - /login/logout
      - /oauth/authorize
      - /oauth/token
      - /oauth/**
      - /system/menu/**
